use school;

CREATE TABLE ALUNO(
Id				INT IDENTITY(1,1) NOT NULL,
Nome			VARCHAR(50) NOT NULL,
CPF				VARCHAR(50) NOT NULL,
Email			VARCHAR(50) NOT NULL,
Telefone		VARCHAR(50) NOT NULL,
Sexo			CHAR(2) NOT NULL,
DataNascimento	DateTime NOT NULL,
IdUsuario       INT NOT NULL,
IdCurso         INT NOT NULL
PRIMARY  KEY(Id)

);

CREATE TABLE USUARIO(
Id				INT IDENTITY(1,1) NOT NULL,
Nome			VARCHAR(50) NOT NULL,
senha           VARCHAR(50) NOT NULL,
PRIMARY  KEY(Id)
);


CREATE TABLE CURSO(
Id				INT IDENTITY(1,1) NOT NULL,
Nome			VARCHAR(50) NOT NULL,
);


CREATE TABLE DICIPLINA(
Id				INT IDENTITY(1,1) NOT NULL,
Nome			VARCHAR(50) NOT NULL,
IdCurso         INT NOT NULL,
IdProfessor     INT NOT NULL
);

CREATE TABLE PROFESSOR(
Id				INT IDENTITY(1,1) NOT NULL,
Nome			VARCHAR(50) NOT NULL,
CPF				VARCHAR(50) NOT NULL,
Email			VARCHAR(50) NOT NULL,
Telefone		VARCHAR(50) NOT NULL,
Sexo			CHAR(2) NOT NULL,
DataNascimento	DateTime NOT NULL
);

